# Site settings
title: "Hi, I'm Wolf480pl"
email: wolf480@interia.pl
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wolf480pl.github.io" # the base hostname & protocol for your site
twitter_username: Wolf480pl
github_username:  Wolf480pl

# Build settings
markdown: kramdown

kramdown:
  input: GFM

# Collections
collections:
  - projects

me_elsewhere:
  - name: Twitter
    profile_url: https://twitter.com/Wolf480pl/
    content: "@Wolf480pl"
  - name: Twister
    content: "@wolf480pl"
  - name: XMPP
    profile_url: xmpp:wolf480pl@neko.im
    content: wolf480pl@neko.im
  - name: Keybase
    profile_url: https://keybase.io/wolf480pl/
    content: wolf480pl
  - name: GitHub
    profile_url: https://github.com/Wolf480pl/
    content: Wolf480pl
